src/ehr_timeline/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'generate-random-events', to: 'pages#generate_random_events', as: 'generate_random_events'
  post 'filter-events', to: 'pages#filter_events', as: 'filter_events'
end

src/ehr_timeline/app/views/pages/home.html.erb
<section id=timeline>
  <h1><%= @events.first.patient.name %></h1>
  <br><br>
  <div class="demo-card-wrapper">
    <% @events.each do |event| %>
      <% if event.is_included %>
        <div class="demo-card demo-card--step<%= event.get_priority %>">
          <div class="head">
            <div class="number-box">
              <span><%= event.get_year %></span>
            </div>
            <h2><span class="small"><i><%= event.get_month_and_date %></i></span>
              <strong><%= event.event_type %></strong></h2>
          </div>
          <div class="body">
            <p><%= event.to_s %></p>
          </div>
        </div>
      <% else %>
        <div class="demo-card demo-card--step<%= event.get_priority %>">
          <div class="head">
            <div class="number-box">
              <span><del><%= event.get_year %></del></span>
            </div>
            <h2><span class="small"><i><del><%= event.get_month_and_date %></del></i></span>
              <del><strong><%= event.event_type %></strong></del></h2>
          </div>
          <div class="body">
            <p><del><%= event.to_s %></del></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

<%= form_tag filter_events_path do %>
<div class="filter-container">
  <div class="filter">
    <h3>Filter by event type</h3>
      <% Event.event_types.each_with_index do |event_type, index| %>
        <%= check_box_tag event_type[0], 'yes', @event_type_filter_values[index], id: event_type[0] %> <%= event_type[0] %>
      <% end %>
      <br>
      <br>
      <%= submit_tag("Filter") %>
  </div>
  <div class="filter">
    <h3>Filter by priority </h3>
      <% (1..4).each_with_index do |i, index| %>
        <%= check_box_tag i.to_s, 'yes', @priority_filter_values[index], id: i %> <%= i %>
      <% end %>
      <br>
      <br>
      <%= submit_tag("Filter") %>
  </div>
</div>
<% end %>

<%= link_to 'Generate random events', generate_random_events_path, :class => "btn btn-outline-primary generate-events-btn" %>